name: Terraform deployment
on: 
  push:
    branches:
      - main

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4
        
      - name: debug-step
        continue-on-error: true
        run: |
          terraform --version 
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.4"
      - name: debug-step2
        run: |
          terraform --version